### ISSUE TITLE
$(nproc)의 의미와 기능

### ISSUE THREAD

**Issue by carmineomiga** [cgiseminar/curriculum#106]
curriculum
-> 파일변환 유틸리티 : HandBrake, Mediainfo(2.7)
-> HandBrake
-> 설치
```
$ ./configure --launch-jobs=$(nproc) --launch
```

여기서 $(nproc)의 기능과 의미가 궁금합니다.

**Comment by khw7096** [comment]
nproc - max number of processes # 한도 숫자 지정

**Comment by khw7096** [comment]
http://faq.hostway.co.kr/Linux_ETC/7179

**Comment by khw7096** [comment]
문서에 설명을 추가함.
https://github.com/cgiseminar/curriculum/blob/master/docs/handbrake.md
