### ISSUE TITLE
github.io에서의 jekyll 오류

### ISSUE THREAD

**Issue by carmineomiga** [cgiseminar/curriculum#107]
![2019-02-27 14-53-56](https://user-images.githubusercontent.com/46209715/53469120-20bdd180-3aa0-11e9-8ea2-3181fb986ef0.png)

**Comment by khw7096** [comment]
jekyll을 설치할 때 3.6.3 보다 높은 버전을 깔면 해결되는 이슈네요. 유민님 노트북에 나중에 jekyll 설치시 높은 버전을 설치해주세요.
