### ISSUE TITLE
VFX R&D 관련 인터뷰 영상들

### ISSUE THREAD

**Issue by kohyuk91** [cgiseminar/curriculum#108]
[[리얼밸리 시즌2-17] 스타워즈로 유명한 ILM의 R&D 엔지니어 장유진의 미국 취업기](https://www.youtube.com/watch?v=B2M9MpAD6mg)

[[리얼밸리 시즌2-16] 디즈니 겨울왕국 VFX 아티스트가 게임 제작자가 되기까지](https://www.youtube.com/watch?v=e9iydsPopj4)

**Comment by khw7096** [comment]
오우~ 고마와용~!

**Comment by baesy0** [comment]
오 감사해요! +4

**Comment by carmineomiga** [comment]
+2
