### ISSUE TITLE
Fedora와 Ubuntu 차이

### ISSUE THREAD

**Issue by carmineomiga** [cgiseminar/curriculum#109]
차이와 커리큘럼에 따라서 설치한 리눅스는 어느쪽인지 궁금합니다.

**Comment by khw7096** [comment]
- 우분투는 데비안 계열이며, 페도라는 레드햇 계열이예요.
- 우리가 사용한  CentOS는 레드헷 계열의 OS이니.. 좀더 페도라쪽에 가까워요. 결국 페도라 리눅스가 레드헷 리눅스가 되고 레드헷 리눅스가 CentOS가 되지요.

**Comment by carmineomiga** [comment]
오호. 그렇군요! 
감사합니다.

**Comment by carmineomiga** [comment]
레드햇과 데비안 비교 설명이 잘 되어있어 올립니다.
https://knucordingmonster.tistory.com/1

**Comment by kybin** [comment]
CG 회사에서 사용하는 리눅스 소프트웨어 대부분이 CentOS 기준으로 만들어져서, 울며 겨자먹기로 쓸 수 밖에 없죠.

**Comment by carmineomiga** [comment]
CG회사가 아닌 곳에서는 데비안 계열을 더 많이 쓰나요?

**Comment by kybin** [comment]
웹 서비스 관련 스타트업들은 대부분 데비안이나 다른 디스트로를 쓸 거라고 생각해요.
전통적으로 시스템이 구축되어있는 회사들은 레드햇 계열을 많이 쓰구요.
