### ISSUE TITLE
steam 설치가 안돼요

### ISSUE THREAD

**Issue by baesy0** [cgiseminar/curriculum#50]
Could not fetch/save url https://negativo17.org/repos/epel-steam.repo to file /etc/yum.repos.d/epel-steam.repo: [Errno 12] Timeout on https://negativo17.org/repos/epel-steam.repo: (28, 'Connection timed out after 30000 milliseconds')

**Comment by khw7096** [comment]
```
yum-config-manager --add-repo=http://negativo17.org/repos/epel-multimedia.repo
```
를 추가하면 설치까지는 되지만 실제 실행시 아래 에러가 발생한다.

```
Running Steam on centos 7 64-bit
STEAM_RUNTIME is enabled automatically
Pins up-to-date!
/home/woong/.local/share/Steam/steam.sh: line 828: /home/woong/.local/share/Steam/ubuntu12_32/steam-runtime/run.sh: 그런 파일이나 디렉터리가 없습니다
Installing breakpad exception handler for appid(steam)/version(0)
/home/woong/.local/share/Steam/steam.sh: line 889: 30221 세그멘테이션 오류 (core dumped) $STEAM_DEBUGGER "$STEAMROOT/$STEAMEXEPATH" "$@"

```

**Comment by khw7096** [comment]
[woong@localhost ~]$  lsb_release -a
LSB Version:	:core-4.1-amd64:core-4.1-noarch
Distributor ID:	CentOS
Description:	CentOS Linux release 7.6.1810 (Core) 
Release:	7.6.1810
Codename:	Core

**Comment by khw7096** [comment]
[woong@localhost ~]$ uname -r
3.10.0-957.1.3.el7.x86_64

**Comment by khw7096** [comment]
이번 생에는 CentOS7.6 에서 게임못하겠네요~!

**Comment by kybin** [comment]
Redhat8 beta가 나왔으니, 2년 정도 뒤에는 할 수 있지 않을까요? ㅎㅎ

**Comment by khw7096** [comment]
그럴지도... Lazypic은 CentOS8 이나오면 바로 갈아타겠어요~
