### ISSUE TITLE
player.md 문서 rv부분 특수문자가 섞여있어요.

### ISSUE THREAD

**Issue by khw7096** [cgiseminar/curriculum#65]
![2019-01-17 10-51-59](https://user-images.githubusercontent.com/1149996/51290064-04ad2600-1a46-11e9-9aa3-f9c427c529bb.png)

문자를 누군가 제거해주었으면 좋겠어요.

**Comment by kokodakdak** [comment]
여러분 화이팅

**Comment by khw7096** [comment]
이 이슈가 해결되어서... 닫습니다.
