### ISSUE TITLE
'Technical Director Course 소개'에 오타가 있어요

### ISSUE THREAD

**Issue by baesy0** [cgiseminar/curriculum#85]
![image](https://user-images.githubusercontent.com/40417084/51435349-b3f13380-1cb8-11e9-95bd-3718be4ae459.png)

**Comment by khw7096** [comment]
오 수정해야겠어요! 고마워요~!

**Comment by khw7096** [comment]
![image](https://user-images.githubusercontent.com/1149996/51438970-e1f56880-1cf6-11e9-8a21-a51d2183619c.png)

수정완료.
