### ISSUE TITLE
git에서 충돌이 일어났을 경우

### ISSUE THREAD

**Issue by baesy0** [cgiseminar/curriculum#95]
충돌이 났다고 해서 Pro Git 89페이지의 '충돌의 기초'를 봤는데요
표준형식에 따라 표시해주는 문서가 있다는데 어디에서 볼 수 있는건가요?

![2019-02-10 16-46-11](https://user-images.githubusercontent.com/40417084/52532854-89057700-2d6e-11e9-9a5c-87c2fd26b0e3.png)

그리고 충돌이 났을 경우 어떻게 하는지 월요일에 다뤄주실 수 있나요:D

**Comment by baesy0** [comment]
해결됐어요!
근데 정신없이 이거적 했더니 제가 뭘 했는지 잘 모르겠어요ㅋㅋ

**Comment by khw7096** [comment]
위 문장은 코드 내부에 <<<<<<<<<<<<< 형태로 적혀있고 에디터로 직접 수정해줘야 해용.
