### ISSUE TITLE
2019년 2월 9일 Rnd 사례발표 추가자료 - 고혁

### ISSUE THREAD

**Issue by kohyuk91** [cgiseminar/curriculum#96]
Chris Zurbrigg is creating Pipeline TD tutorials - https://www.patreon.com/zurbrigg/overview
월결제 방식으로 운영되고 있는 튜토리얼 사이트입니다.
Pipeline TD를 위한 양질의 튜토리얼이 많이 올라와 있습니다.
Maya Python, PySide, API 등 아직은 마야 관련 자료가 대다수 이지만,
뉴크, 블랜더 등 다른 DCC툴도 다룰 예정이라고 하니 기대해볼만 합니다!

**Comment by khw7096** [comment]
학생들에게 전달했어요. 고마워용.
